ecommerce1/ecommerce1/cartapp/urls.py
from django.urls import path
from . import views
app_name = 'cartapp'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.cart_item_delete, name='cart_item_delete'),
    path('payment/', views.payment, name='payment'),
    path('success/', views.payment_success, name='payment_success'),
]

ecommerce1/ecommerce1/ecommerce1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp',include('ecommerceapp.urls')),
    path('searchapp/',include('searchapp.urls')),
    path('cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce1/ecommerce1/ecommerceapp/urls.py
from django.urls import path

from . import views
app_name = 'ecommerceapp'
urlpatterns = [
    path('', views.AllCategories, name='AllCategories'),
    path('<slug:c_slug>/',views.AllCategories,name='product'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProductDetails,name='ProductDetails'),
]

ecommerce1/ecommerce1/searchapp/urls.py
from django.urls import path

from . import views
app_name = 'searchapp'
urlpatterns = [
    path('',views.SearchResults,name="SearchResults")
]

ecommerce1/ecommerce1/cartapp/models.py
from django.db import models
from ecommerceapp.models import Product
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce1/ecommerce1/ecommerceapp/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecommerceapp:product',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerceapp:ProductDetails',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def __str__(self):
        return '{}'.format(self.name)

ecommerce1/ecommerce1/searchapp/models.py
from django.db import models

# Create your models here.

ecommerce1/ecommerce1/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, CartItem
from ecommerceapp .models import Product
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cartapp:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')
def cart_item_delete(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')
def payment(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'payment.html',dict(cart_items=cart_items,total=total,counter=counter))
def payment_success(request):
    return render(request,'success.html')

ecommerce1/ecommerce1/ecommerceapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def AllCategories(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,8)
    try:
        page = int (request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage,InvalidPage):
        products = paginator.page(paginator .num_pages)
    return render(request, "category.html", {'category': c_page, 'products': products})

def ProductDetails(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request, "product.html", {'product': product})
from django.shortcuts import render, get_object_or_404
from .models import Product

ecommerce1/ecommerce1/searchapp/views.py
from django.shortcuts import render
from ecommerceapp.models import Product
from django.db.models import Q
def SearchResults(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query': query,'products': products})

ecommerce1/ecommerce1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecommerce1/ecommerce1/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
 This is cart page from here you can check out items
{% endblock %}

{% block title %}
cart-cartopia
{% endblock %}

{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center"><br>
            <h1 class="text-center my_title">
                Your Cart Is Empty
            </h1>
            <p class="text-center">
                <a href="{% url 'ecommerceapp:AllCategories' %}">click here to add items</a>
            </p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center"><br>
            <h1 class=" text-center my_title">
                Your Shopping Cart
            </h1>
        </div>
    </div><br><br>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">
                            Your items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="{% url 'ecommerceapp:ProductDetails' cart_item.product.category.slug cart_item.product.slug %}">
                                    <img src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left custom_image" height="105px" width="155px">
                                </a>
                            </td>
                            <td class="text-left">
                                {{cart_item.product.name}}<br>
                                SKU: {{cart_item.product.id}}<br>
                                price: ₹{{cart_item.product.price}}<br>
                                QTY: {{cart_item.quantity}} x {{cart_item.product.price}}
                            </td>
                            <td>
                                ₹{{cart_item.sub_total}}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                                <td>
                                    <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus"></i></a>
                                    &nbsp; <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                                    &nbsp; <a href="{% url 'cartapp:cart_item_delete' cart_item.product.id %}" class="custom_symbol"><i class="fa-solid fa-trash"></i></a>
                                </td>
                            {% else %}
                                <td>
                                    &nbsp; <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                                    &nbsp; <a href="{% url 'cartapp:cart_item_delete' cart_item.product.id %}" class="custom_symbol"><i class="fa-solid fa-trash"></i></a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <br><br>PLease review your shopping cart items before processing with the order payment<br><br><br>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <br><br>Total price of the products in the cart : <strong>{{total}}</strong><br><br><br>
                        </td>
                    </tr>
                </tbody>
            </table><br><br>
            <div class="mx-auto">
                <a href="{% url 'ecommerceapp:AllCategories' %}" class="btn btn-success btn-block my_custom_button">
                    Continue Shopping <i class="fa-solid fa-cart-shopping"></i>
                </a>
                <a href="{% url 'cartapp:payment' %}" class="btn btn-primary btn-block my_custom_button">Make Payment <i class="fa-solid fa-credit-card"></i></a>
            </div>
        </div>
    </div><br><br><br>
{% endif %}
{% endblock %}

ecommerce1/ecommerce1/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description | truncatewords:150}}
    {% else %}
        This is our categories
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}}-Cartopia
    {% else %}
        Category
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx_auto">
                    <p><a href="{% url 'ecommerceapp:AllCategories' %}">our products</a> </p>
                </div>
            </div>
        </div>
    {% endif %}
    {% if category %}
        <div class="mx_auto">
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" height="700" width="1000">
        </div><br>
        <div>
            <h3 class="text-center my_title">{{category.name}}</h3>
            <p class="text-justify">{{category.description}}</p>
        </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'image/banner2.png' %}" alt="our products" width="1300px" height="500px">
        </div><br>
        <div><br>
            <h3 class="text-center"><u>our collections</u></h3><br>
            <p class="text-justify about"><b>Cartopia</b> is your one-stop destination for all your fashion needs. Established in 2023,
                                    we offer a vast collection of top-quality fashion products that cater to every style and taste.
                                    Our website is designed to provide a seamless shopping experience, with an easy-to-use interface that allows
                                    you to browse through our extensive collection of fashion items.
                                    At Cartopia, we understand the importance of quality and genuineness when it comes to fashion products.
                                    That's why we ensure that all our products are made from the finest materials and are sourced
                                    from reputable brands and manufacturers. Our team of experts carefully curates each
                                    item to ensure that you get only the best and most authentic products.
                                    Whether you're looking for trendy clothing, stylish accessories, or the latest footwear,
                                    you can trust Cartopia to deliver. We offer a wide range of products that cater to
                                    different budgets and styles, so you're sure to find something that suits your needs.
                So why wait?<br><br> <b>Explore our website today and discover the best in fashion with Cartopia!</b>
            </p>
        </div><br>
    {% endif %}


<style>
.card {
    transition: transform 0.2s ease-in-out;
}

.card:hover {
    transform: scale(1.05);
}
.card-body {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    height: 100%;
}
.card-title {
    font-size : 14px;
    text-transform : uppercase;
    letter-spacing : .1em;
}

.card-text {
  font-size: 1rem;
  margin-top: auto;
}
</style>




<div class="row">
    {% for i in products.object_list %}
        <div class="col-md-3">
            <div class="card mb-4" style="height: 20rem;">
                <a href="{{ i.get_url }}"><img class="card-img-top" src="{{ i.image.url }}" alt="{{ i.name }}" height="200px"></a>
                <div class="card-body">
                    <h6 class="card-title">{{ i.name }}</h6>
                    <h6>Stocks Left : {{i.stock}} Nos</h6>
                    <p class="card-text"><b>₹{{ i.price }}</b></p>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
</div>
<div class="row">
        {% endif %}
    {% endfor %}
</div>
<div class="mx-auto">
    {% if products.paginator.num_pages %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {%endif%}">{{pg}}</a>
            {% endfor %}
        </div>
    {% endif %}
</div><br>
{% endblock %}

ecommerce1/ecommerce1/templates/footer.html
<style>
    html {
        position: relative;
        min-height: 100%;
    }
    body {
        margin: 0;
        padding-bottom: 130px; /* Set padding equal to footer height */
    }
    .footer {
        position: absolute;
        left: 0;
        bottom: 0;
        width: 100%;
        height: 130px; /* Set footer height */
        background-color: #878f99;
        color: #0066ff;
        text-align: center;
        padding-top: 20px;
    }
    /* Add a class to the container for short content */
    .short-content {
        min-height: calc(30vh - 50px);
    }
</style>

<body>
    <div class="container">
        <div class="content short-content">
        </div>
    </div>
    <div class="footer">
        <p style="color:white;">
            contact us : cartopia@gmail.com<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;salamava66@gmail.com<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8113955183
        </p>
        <p>&copy; CARTOPIA pvt ltd. All rights reserved</p>
    </div>
</body>

ecommerce1/ecommerce1/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:AllCategories' %}"><img src="{% static 'image/logo1.png' %}" alt="logoimage" width="270px" height="80px"></a>
    </center>
</header><br>

ecommerce1/ecommerce1/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecommerceapp:AllCategories' %}"><i class="fa-solid fa-house"></i></i></a>
                </li>
                <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        shop
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'ecommerceapp:AllCategories' %}">View all products</a></li>
                        {% for i in links %}
                            <li><a class="dropdown-item" href="{{i.get_url}}">{{i.name}}</a></li>

                        {% endfor %}
                    </ul>
                </li>
                {% if item_count > 0 %}
                    <li class="nav-item">
                        <a href="{% url 'cartapp:cart_detail' %}" class="nav-link "><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'searchapp:SearchResults' %}" method="get">
            {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
    </div>
</nav>
<br>

ecommerce1/ecommerce1/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Payment section
{% endblock %}

{% block title %}
    payment-cartopia
{% endblock %}

{% block content %}
<div>
    <div class="text-center my_head">
        Payment
        total money to pay {{total}}
    </div><br>
</div>
<form method="post" id="payment-form">
    {% csrf_token %}
    <div class="form">
        <div class="form form_title">
            <h5 class="text-center my_head">
                Payment details
            </h5>
        </div><br><br>
        <div class="container">
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-right">
                    <h4>
                        <u>Address details</u>
                    </h4><br>
                    <input type="text" placeholder="Enter your name" name="name">&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" placeholder="Address lane one" name="lane1"><br><br><br>
                    <input type="text" placeholder="Address lane two" name="lane2">&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" placeholder="Address lane three" name="lane3"><br><br><br>
                    <input type="text" placeholder="Address lane four" name="lane4">&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" placeholder="Post" name="post"><br><br><br>
                    <input type="number" placeholder="Address PIN code" name="pin">&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" placeholder="Landmark" name="landmark"><br><br><br>
                    <input type="text" placeholder="District" name="district">&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" placeholder="State" name="state"><br><br><br>
                    <input type="number" placeholder="Mobile number" name="number">&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="email" placeholder="E-Mail" name="email">
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-right">
                    <h4>
                        <u>Card details</u>
                    </h4><br>
                    <input type="text" placeholder="Enter your name in card" name="card_name"><br><br><br>
                    <input type="date" placeholder="Enter DOB" name="DOB"><br><br><br>
                    <input type="number" placeholder="Enter your card number" name="card"><br><br><br>
                    <input type="number" placeholder="Enter CVV" name="CVV"><br><br><br>
                    <p>Expire date</p><input type="date" placeholder="Expire date" name="exp"><br><br><br>
                    <a href="{% url 'cartapp:payment_success' %}" class="btn btn-success">Make payment of {{total}}</a>
                </div>
            </div>
        </div>
    </div>
</form>


{% endblock %}

ecommerce1/ecommerce1/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{product.description | truncatewords:150}}
{% endblock %}

{% block title %}
    {% if product %}
        {{product.name}}-Cartopia
    {% endif %}
{% endblock %}

{% block content %}

    <div>
        <div>
            <p><a href="{% url 'ecommerceapp:AllCategories' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
        </div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6"><br>
            <img src="{{product.image.url}}" alt="{{product.name}}" height="350px" width="500px">
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h2 class="product-name">{{product.name}}</h2>
                <p class="product-price">₹{{product.price}}</p>
                <p class="product-description">{{product.description}}</p>
                <div style="position: absolute;">
                    {% if product.stock <= 0 %}
                        <p><b>Out Of Stock</b></p>
                    {% else %}
                        <div>
                            <a class="btn btn-success" href="{% url 'cartapp:add_cart' product.id %}">Add to <i class="fa-solid fa-cart-shopping"></i></a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br>


{% endblock %}

ecommerce1/ecommerce1/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Search items you can find here
{% endblock %}
{% block title %}
    search - cartopia
{% endblock %}
{% block content %}
<div>
  <p class="text-center my_search_text">you have searched for <b>"{{query}}"</b></p>
</div>

<style>
.card {
    transition: transform 0.2s ease-in-out;
}

.card:hover {
    transform: scale(1.05);
}
.card-body {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    height: 100%;
}
.card-title {
    font-size : 14px;
    text-transform : uppercase;
    letter-spacing : .1em;
}

.card-text {
  font-size: 1rem;
  margin-top: auto;
}
</style>

<div class="row">
    {% for i in products %}
        <div class="col-md-3">
            <div class="card mb-4" style="height: 20rem;">
                <a href="{{ i.get_url }}"><img class="card-img-top" src="{{ i.image.url }}" alt="{{ i.name }}" height="200px"></a>
                <div class="card-body">
                    <h6 class="card-title">{{ i.name }}</h6>
                    <h6>Stocks Left : {{i.stock}} Nos</h6>
                    <p class="card-text"><b>₹{{ i.price }}</b></p>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">No result found</p>
            </div>
    {% endfor %}
</div>
{% endblock %}

ecommerce1/ecommerce1/templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
 Payment successful page
{% endblock %}

{% block title %}
payment successful
{% endblock %}

    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 50px;
        }
        h1 {
            font-size: 36px;
            color: #008000;
            text-transform: uppercase;
        }
        p {
            font-size: 22px;
            color: #333;
        }
        a {
            color: #0066ff;
            text-decoration: none;
            font-weight: bold;
        }
    </style>
{% block content %}
    <div class="text-center">
        <h1>Payment Successful</h1><br>
        <i class="fa-sharp fa-regular fa-circle-check fa-2xl"></i><br><br><br>
        <p>Thank you for your payment. Your transaction was successful.</p>
        <p>You will receive a confirmation email shortly.</p>
        <br><i class="fa-regular fa-face-smile fa-2xl"></i><br><br><br>
        <a href="{% url 'ecommerceapp:AllCategories' %}" class="btn btn-primary">Back to homepage</a>
    </div>
{% endblock %}