ecommerce1/ecommerce1/cartapp/urls.py
from django.urls import path
from . import views
app_name = 'cartapp'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.cart_item_delete, name='cart_item_delete'),
    path('payment/', views.payment, name='payment'),
    path('success/', views.payment_success, name='payment_success'),
]

ecommerce1/ecommerce1/ecommerce1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp',include('ecommerceapp.urls')),
    path('searchapp/',include('searchapp.urls')),
    path('cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce1/ecommerce1/ecommerceapp/urls.py
from django.urls import path

from . import views
app_name = 'ecommerceapp'
urlpatterns = [
    path('', views.AllCategories, name='AllCategories'),
    path('<slug:c_slug>/',views.AllCategories,name='product'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProductDetails,name='ProductDetails'),
]

ecommerce1/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
 This is cart page from here you can check out items
{% endblock %}

{% block title %}
cart-cartopia
{% endblock %}

{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center"><br>
            <h1 class="text-center my_title">
                Your Cart Is Empty
            </h1>
            <p class="text-center">
                <a href="{% url 'ecommerceapp:AllCategories' %}">click here to add items</a>
            </p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center"><br>
            <h1 class=" text-center my_title">
                Your Shopping Cart
            </h1>
        </div>
    </div><br><br>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">
                            Your items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="{% url 'ecommerceapp:ProductDetails' cart_item.product.category.slug cart_item.product.slug %}">
                                    <img src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left custom_image" height="105px" width="155px">
                                </a>
                            </td>
                            <td class="text-left">
                                {{cart_item.product.name}}<br>
                                SKU: {{cart_item.product.id}}<br>
                                price: ₹{{cart_item.product.price}}<br>
                                QTY: {{cart_item.quantity}} x {{cart_item.product.price}}
                            </td>
                            <td>
                                ₹{{cart_item.sub_total}}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                                <td>
                                    <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus"></i></a>
                                    &nbsp; <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                                    &nbsp; <a href="{% url 'cartapp:cart_item_delete' cart_item.product.id %}" class="custom_symbol"><i class="fa-solid fa-trash"></i></a>
                                </td>
                            {% else %}
                                <td>
                                    &nbsp; <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                                    &nbsp; <a href="{% url 'cartapp:cart_item_delete' cart_item.product.id %}" class="custom_symbol"><i class="fa-solid fa-trash"></i></a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <br><br>PLease review your shopping cart items before processing with the order payment<br><br><br>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <br><br>Total price of the products in the cart : <strong>{{total}}</strong><br><br><br>
                        </td>
                    </tr>
                </tbody>
            </table><br><br>
            <div class="mx-auto">
                <a href="{% url 'ecommerceapp:AllCategories' %}" class="btn btn-success btn-block my_custom_button">
                    Continue Shopping <i class="fa-solid fa-cart-shopping"></i>
                </a>
                <a href="{% url 'ecommerceapp:AllCategories' %}" class="btn btn-primary btn-block my_custom_button">Make Payment <i class="fa-solid fa-credit-card"></i></a>
            </div>
        </div>
    </div><br><br><br>
{% endif %}
{% endblock %}